# Transformacion 7

```{r echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

Sys.Date()
```

## Funciones estadistica básicas:

Tarea de grupo.

Preparar un .rmd con la explicaciones de como utilizar la función mencionado abajo. Debe incluir

1.  La definición de la función en palabra y matemática.
2.  un script sencillo (con pocos datos) (uno o más ejemplos) para explicar la función
3.  un script con los datos de "vuelos" o de "Covid-19 de PR".
4.  a las 2:20pm cada grupo presentará su trabajo.
5.  Después de la clase cada grupo, mejorará su .rmd con los comentarios recibidos.\
6.  Domingo se subirá el .rmd y el .html en MSTeam (cada estudiante lo subirá: tendra el nombre de cada estudiante en el trabajo)
7.  El profesor revisará los trabajos y subsiguiente se distribuirá los .rmd y html a los estudiantes.

-   IQR() \## G1

-   mad() \## G2

-   first() \## G3

-   last() \## G3

-   quantile() \## G4

-   signif() \## G5

    -   min()

-   max()

-   mean()

-   sd() \*\*\*

1.  **Ejercicios**:

Hacer los ejercicios en la sección 5.7.1 del libro en español

------------------------------------------------------------------------









