# Ecuaciones Matemáticas {#math-sci}


```{r echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

Sys.Date()
```

<!-- Required to number equations in HTML files -->
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>

## Ecuaciones matemática

*TeX* es la mejor manera de escribir funciones matemáticas en R. Donald Knuth diseñó el paquete \TeX\ cuando se sintió frustrado por el tiempo que les tomaba a los tipógrafos y terminar su libro, que contenía mucha funciones matemática. Una característica interesante de _R Markdown_ es su capacidad para leer código LaTeX directamente. 


Si está haciendo una tesis, artículo cientíco, presentaciones o quiere aclarar en su documento las funciones que estas usando, típicamente esto involucrará muchas ecuaciones matemáticas. Por consecuencia querrá leer la siguiente sección que ha sido comentada. 


***

### Matemática y Física

$$
\sum_{j=1}^n (\delta\theta_j)^2 \leq {{\beta_i^2}\over{\delta_i^2 + \rho_i^2}}
\left[ 2\rho_i^2 + {\delta_i^2\beta_i^2\over{\delta_i^2 + \rho_i^2}} \right] \equiv \omega_i^2
$$



De Informational Dynamics, tenemos lo siguiente (Dave Braden):

Después de _n_ tales encuentros, la densidad posterior de $\theta$ es

$$
\pi(\theta|X_1< y_1,\dots,X_n<y_n) \varpropto \pi(\theta) \prod_{i=1}^n\int_{-\infty}^{y_i}
   \exp\left(-{(x-\theta)^2\over{2\sigma^2}}\right)\ dx
$$



Otra Ecuaciones

$$
\det\left|\,\begin{matrix}%
c_0&c_1\hfill&c_2\hfill&\ldots&c_n\hfill\cr
c_1&c_2\hfill&c_3\hfill&\ldots&c_{n+1}\hfill\cr
c_2&c_3\hfill&c_4\hfill&\ldots&c_{n+2}\hfill\cr
\,\vdots\hfill&\,\vdots\hfill&
  \,\vdots\hfill&&\,\vdots\hfill\cr
c_n&c_{n+1}\hfill&c_{n+2}\hfill&\ldots&c_{2n}\hfill\cr
\end{matrix}\right|>0
$$
***
***

Lapidus y Píndaro, Solución numérica de ecuaciones diferenciales parciales en ciencia y Ingeniería. Página 54

$$
\int_t\left\{\sum_{j=1}^3 T_j \left({d\phi_j\over dt}+k\phi_j\right)-kT_e\right\}w_i(t)\ dt=0,
   \qquad\quad i=1,2,3.
$$


Funciones de ponderación del método L\&P Galerkin. Página 55

$$
\sum_{j=1}^3 T_j\int_0^1\left\{{d\phi_j\over dt} + k\phi_j\right\} \phi_i\ dt
   = \int_{0}^1k\,T_e\phi_idt, \qquad i=1,2,3 $$

Otra de L\&P (p145)

$$
\int_{-1}^1\!\int_{-1}^1\!\int_{-1}^1 f\big(\xi,\eta,\zeta\big)
   = \sum_{k=1}^n\sum_{j=1}^n\sum_{i=1}^n w_i w_j w_k f\big( \xi,\eta,\zeta\big).
$$

Otra de L\&P (p126)

$$
\int_{A_e} (\,\cdot\,) dx dy = \int_{-1}^1\!\int_{-1}^1 (\,\cdot\,) \det[J] d\xi d\eta.
$$

## Símbolos de LATEX

Pueden encontrar los símbolos de Latex matemáticos en la siguiente pagina web: https://oeis.org/wiki/List_of_LaTeX_mathematical_symbols



-->

## Química 101: Símbolos


Las fórmulas químicas se verán mejor si no están en cursiva. Evite la cursiva automática del modo matemático en LaTeX usando el argumento `$\mathrm{fórmula aquí}$`, con su fórmula dentro de las llaves. (Observe el uso de comillas invertidas aquí que encierran texto y que actúa como código para ver el código original).


Entonces, $\mathrm{Fe_2^{2+}Cr_2O_4}$ es escrito como `$\mathrm{Fe_2^{2+}Cr_2O_4}$`.


Esta fomula es parte de la frase $$\mathrm{Fe_2^{2+}Cr_2O_2}$$


 - Exponente or Sobrescrito: $\mathrm{O^-}$ y se escribe como `$\mathrm{O^-}$`

 - Subíndice: $\mathrm{CH_4}$ y se escribe como `$\mathrm{CH_4}$`

 - Para apilar números o letras como en $\mathrm{Fe_2^{2+}}$, primero se define el subíndice y luego el superíndice y se escribe como `$\mathrm{Fe_2^{2+}}$`. 

 - punto se usa la palabra **bullet**: 
 
$\mathrm{CuCl}$ $\bullet$ $\mathrm{7H_{2}O}$  
 
 donde se escribe como `CuCl $\bullet$ $\mathrm{7H_{2}O}$`


## Símbolos comunes

- Delta: $\Delta$ y se escribe como `$\Delta

 - Gamma mayúscula $\Gamma$

 - Gamma minúscula $\gamma$

 - Aquí esta mi súper formula de $\phi$ que voy a usar en el examen de matemáticas.

 - Flecha de Reacción: $\longrightarrow$ or  $\xrightarrow{solution}$ y se escribe como `$\longrightarrow$` or  `$\xrightarrow{solution}$`

 - Flecha de Resonancia: $\leftrightarrow$ y se escribe como `$\leftrightarrow$`

 - Flechas de reacción reversibles: $\rightleftharpoons$ y se escribe como `$\rightleftharpoons$`

### Típografica de reaciones

Es posible que desees poner tu reacción en un entorno de ecuaciones, lo que significa que LaTeX colocará la reacción donde encaje y numerará las ecuaciones por ti. 


\begin{equation}
  \mathrm{C_6H_{12}O_6  + 6O_2} \longrightarrow \mathrm{6CO_2 + 6H_2O}
  (\#eq:reaction)
\end{equation}


y se escribe como 



````markdown
\begin{equation}
  \mathrm{C_6H_{12}O_6  + 6O_2} \longrightarrow \mathrm{6CO_2 + 6H_2O}
  (\#eq:reaction)
\end{equation}
````

Podemos hacer referencia a esta reacción de combustión de glucosa mediante la ecuación \@ref(eq:reaction).

### Otros ejemplos de reacciones

$\mathrm{NH_4Cl_{(s)}}$ $\rightleftharpoons$ $\mathrm{NH_{3(g)}+HCl_{(g)}}$

y se esscribe como

`$\mathrm{NH_4Cl_{(s)}}$ $\rightleftharpoons$ $\mathrm{NH_{3(g)}+HCl_{(g)}}$`

$\mathrm{MeCH_2Br + Mg}$ $\xrightarrow[abajo]{ariba}$ $\mathrm{MeCH_2\bullet Mg \bullet Br}$

y se escribe como 

`$\mathrm{MeCH_2Br + Mg}$ $\xrightarrow[abajo]{ariba}$ $\mathrm{MeCH_2\bullet Mg \bullet Br}$`


## Física


Muchos de los símbolos que necesitará se pueden encontrar en la página de matemáticas.

<https://web.reed.edu/cis/help/latex/math.html> y la guía completa de símbolos LaTeX (<https://mirror.utexas.edu/ctan/info/symbols/comprehensive/symbols-letter.pdf>).

## Biología

Probablemente encontrará los recursos en <https://www.lecb.ncifcrf.gov/~toms/latex.html> útil, particularmente los enlaces a bsts de varias revistas. Quizás también le interese TeXShade para composición tipográfica de nucleótidos (<https://homepages.uni-tuebingen.de/beitz/txe.html>). Asegúrese de leer el capítulo anterior sobre gráficos y tablas.

La formula del promedio 



$\mu=\frac{\sum{x}_{i}}{n}$ se escribe asi `$\mu=\frac{\sum{x}_{i}}{n}$`

NOTE la diferencia en tipo de letra.........entre las dos formulas

Nota aqui que la formaula se escribe en la oración $\mathrm{\mu=\frac{\sum{x}_{i}}{n}}$ se escribe asi `$\mathrm{\mu=\frac{\sum{x}_{i}}{n}}$`

Pero si quiere que la formula este en una linea aparte lo escribe así dentro de `\begin{equation}`, la formula aquí y termina con `\end{equation}`

\begin{equation}
  \mathrm{\mu=\frac{\sum{x}_{i}}{n}}
  (\#eq:promedio)
\end{equation}


$s^{2}=\frac{\sum (x_{i}-\bar{x})^2}{n-1}$

Sitios en el web para preparar las ecuaciones Latex

1. <https://latex.codecogs.com/eqneditor/editor.php>

2. <https://latexeditor.lagrida.com>

3. <https://www.hostmath.com>

4. <https://www.overleaf.com/learn/latex/Mathematical_expressions>
