# (Appendix) Ejercicios 1 {.unnumbered}

------------------------------------------------------------------------

## Capitulo de Transformación de Datos {.unnumbered}

## Ejercicios con destrezar de aplicar algunas funciones de transformaciones de datos {.unnumbered}

### Para tener los puntos tiene que enseñar TODOS los scripts, los resultados y explicar en palabra los que encontró dentro de un documento bien organizado. {.unnumbered}

```{r}
library(datos)
attach(bateadores)
library(tidyverse)
library(gt)
```

Use el data frame de "bateadores" en el paquete "datos".

```{r}

gt(head(bateadores, n=3))

```

------------------------------------------------------------------------

## 1. Busca el bateador que tuvo más carreras en cualquier año {.unnumbered}

```{r, eval=FALSE, echo=FALSE}

max(bateadores$carreras)

bateadores |> select(id_jugador, carreras) |> 
  arrange(desc(carreras)) |> 
  slice_max(carreras)

```

------------------------------------------------------------------------

## 2. ¿Cual es el nombre del bateador (id_jugador) que estuvo más veces "al_bate"? Prepara una lista del bateador más frecuente al bate al menos {.unnumbered}

```{r, eval=FALSE, echo=FALSE}

bateadores |> select(id_jugador, al_bate) |> 
  arrange(desc(al_bate))

```

------------------------------------------------------------------------

## 3. ¿Cuales son las "ligas" de baseball (pelota) que estan incluida en este archivo? {.unnumbered}


```{r, eval=FALSE, echo=FALSE}

unique(bateadores$id_liga)
```

------------------------------------------------------------------------

## 4. Selecciona los años (1900, 1950, 2000 y 2020) y jonrones y hacer una tabla por año que demuestra el máximo de jonrones para cada año {.unnumbered}

¿Cual fue el máximo de jonrones por año para los años selecionado? Haga una lista.

```{r, eval=FALSE, echo=FALSE}
unique(bateadores$id_anio)
bateadores |> select(id_anio, cuadrangulares) |> 
  filter(id_anio %in% c(1900, 1950, 2000, 2020)) |> 
  group_by(id_anio) |> 
  summarise(max=max(cuadrangulares))
  
```

------------------------------------------------------------------------

## 5. Haz una tabla de la los jugadores que juraron más años {.unnumbered}

-   ¿Cual es el jugador que ha jugado más años?

```{r, eval=FALSE, echo=FALSE}
bateadores |> select(id_jugador, id_anio) |> 
  group_by(id_jugador) |> 
  summarise(count_years= sum(duplicated(id_jugador))) |> 
  arrange(desc(count_years))
```

------------------------------------------------------------------------

## 6. Selecciona solamente la liga "AL", los años desde de 2000 en adelande, y determina cual es la suma de "carreras" anotadas por cada equipo. {.unnumbered}

-   a)  ¿Cual es el equipo que tiene mayor carreras?

-   b)  ¿Cual es el equipo que tiene menor carreras?

-   c)  Como explica que ese equipo tiene tan poca carreras.
        Piensa en un tipo de "Data wrangling", que podria explicar esto (BONO), si lo resuelve tendrá un bono

```{r, eval=FALSE, echo=FALSE}
bateadores |> select(id_liga, id_anio, id_equipo, carreras) |> 
  filter(id_liga == "AL") |> 
  filter(id_anio %in% c(2000:2020)) |> 
  group_by(id_equipo) |> 
  summarise(sum=sum(carreras))
```

------------------------------------------------------------------------

```{r, eval=FALSE, echo=FALSE}
bateadores |> select(id_liga, id_anio, id_equipo) |> 
  filter(id_liga == "AL") |> 
  filter(id_anio %in% c(2000:2020)) |> 
  group_by(id_equipo) |> 
  summarize(n=n_distinct(id_anio))


```


------------------------------------------------------------------------