# (Appendix) Ejercicios 2 {.unnumbered}

------------------------------------------------------------------------

## Ejercicios para las funciones de transformaciones 2 {-}


## Seleccione los siguientes datos sobre COVID en PR {-}

### LEEN bien lo que estoy pidiendo. El nombre de las columnas pueden engañar!!! {-}

```{r}
library(tidyverse)
library(data.table)
url_COVID_PR=fread("https://raw.githubusercontent.com/rafalab/pr-covid/master/dashboard/data/DatosMortalidad.csv")
```




```{r}
library(gt)
Covid=url_COVID_PR
gt(tail(Covid, n=2))
```



## 1. Calcular el promedio de Muertes por dia de nuevos muertos desde el comienzo hasta el ultimo dia del archivo {-}


```{r, eval=FALSE, echo=FALSE}
Covid |> dplyr::select(IncrementoMuertes) |> 
  summarize(mean=mean(IncrementoMuertes, na.rm = TRUE))
```


## 2. ¿Cual es la máximo de nuevos casos en un día {-}

```{r, eval=FALSE, echo=FALSE}
Covid |> dplyr::select(IncCasosSaludNuevo) |> 
  summarize(mean=mean(IncCasosSaludNuevo, na.rm = TRUE))

```


## 3. ¿Calcular la cantidad cumulativa de numero de camas CamasICU {-}

 - Enseñe solamente las ultimas 4 filas

```{r, eval=FALSE, echo=FALSE}
library(MASS)
library(GMCM) # cummean
library(cumstats)
Covid |> dplyr::select(Ventiladores) |> 
         mutate(suma=cummean(Ventiladores)) %>% 
         mutate(Var_cum=cumstats::cumvar(Ventiladores)) 


```



```{r, eval=FALSE, echo=FALSE}
cum_x=Covid |> dplyr::select(Ventiladores) |> 
         mutate(suma=cummean(replace_na(Ventiladores, 0))) %>% 
         mutate(Var_cum=cumstats::cumvar(replace_na(Ventiladores, 0)))

tail(cum_x, n=4)
```


## 4. Haz una grafica de la varianza y como cambia atravez del tiempo. {-}

 - usa puntos para cada fecha
 - añade una regresión LOESS
 - cambia los nombres de los ejes para algo más claro
 - los colores de los puntos
 - cambia el color de la linea


```{r, eval=FALSE, echo=FALSE}
cum_x$order=c(1:587)

ggplot(cum_x, aes(order, Var_cum))+
  geom_point()+
  geom_smooth(color="red")
```


------------------------------------------------------------------------



