# Appendix C

```{r echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

Sys.Date()
```
------------------------------------------------------------------------

```{r}
library(readr)
HIV <- read_csv("HIV.csv")


HIV
```








```{r}
library(tidyverse)
```

https://www.stat.berkeley.edu/~s133/dates.html

```{r}



HIV$dob=as.Date(format(as.Date(HIV$dob,format="%m/%d/%y"), "19%y%m%d"), "%Y%m%d")


HIV

```

## Calculate the age of individuals when they were diagnosed with HIV {-}

## Calculate the time between the date of diagnosis of HIV and the date of death. {-}






```{r}

HIV= HIV |>  
  mutate(date_d=mdy(date_of_death),
         hiv_d = mdy(hiv_date))

HIV

```


```{r}
HIV1 <- HIV %>% 
  mutate(hiv_date = mdy(hiv_date))

HIV1

HIV2 <- HIV1 %>% 
  mutate(edad = dob %--% hiv_date / years())

HIV2


```

```{r}
HIV3 <- HIV2 %>% 
  mutate(date_of_death = mdy(date_of_death))

HIV3

HIV4 <- HIV3 %>% 
  mutate(diagnosed_death = hiv_date %--% date_of_death / years())

HIV4
```


## Calculate the difference in life between the date of diagnosis and death {-}


```{r}

HIV$months= floor(time_length(difftime(HIV$date_d, HIV$hiv_d), "months"))
HIV$months






HIV %>%
  mutate(Period_HIV_death = as.duration(hiv_d %--% date_d)) |> 
  summarise(mean_time=mean(Period_HIV_death)) 
```


------------------------------------------------------------------------






